apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: name2
spec:
  type: NodePort
  selector:
    app: bdapipersona
  ports:
  - protocol: TCP
    name: http-pod-mysql
    port: 3306
    targetPort: 3306