apiVersion: v1
kind: Service
metadata:
  name: svcapi
  namespace: name2
spec:
  ports:
  - port: 8090
    name: svcapi
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-apipersona
  type: LoadBalancer
