apiVersion: v1
kind: Pod
metadata:
  name: stack-api-persona-2
  namespace: default
  labels:
    app: api-persona-2
    version: v1
spec:
  containers:
   - name: api-persona 
     image: rramirezc21/imagen-api-persona:1.0.0
     ports:
        - containerPort: 8080
     env:
        - name: host
          value: localhost
        - name: port
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        - name: MYSQL_ROOT_HOST
          value: "%"
     resources:
      requests:
        memory: "512Mi"
        cpu: "50m" # 1000m = 1
      limits:
        memory: "512Mi"
        cpu: "500m"
   - name: bd   
     image: wjma90/clase-1-mysql
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: toor
     - name: MYSQL_ROOT_HOST
       value: "%"
     ports:
        - containerPort: 3306
     resources:
      requests:
        memory: "300Mi"
        cpu: "80m"
      limits:
        memory: "300Mi"
        cpu: "80m"
  restartPolicy: OnFailure #valores posibles -> Always, OnFailure, Never
