apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: name1
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
    targetPort: 3306
  selector:
    app: bdapipersona
  type: ClusterIP
