apiVersion: v1
kind: Service
metadata:
  name: svcapi
  namespace: name1
spec:
  ports:
  - port: 8090
    name: svcapi
    protocol: TCP
    targetPort: 8080
  selector:
    app: rs-api-persona
  type: ClusterIP
